### ISSUE TITLE
Compile error on Rasperry Pi 4

### ISSUE THREAD

**Issue by Jumbotroll** [ea3ihi/DMRStation#10]
I added ./src/codec2_client.o \ in makefile and then it copiled ok.

OBJS += \
./src/ambe_client.o \
./src/audio.o \
./src/config.o \
./src/dmr.o \
./src/dmrids.o \
./src/fw_mbelib.o \
./src/lastheard.o \
./src/main.o \
./src/net.o \
./src/ptt.o \
./src/resources.o \
./src/talkgroup.o \
./src/codec2_client.o \

**Comment by ea3ihi** [comment]
Thanks!, makefile updated!
