### ISSUE TITLE
No libcrypto in Ubuntu 20.04?

### ISSUE THREAD

**Issue by mlforcada** [ea3ihi/DMRStation#11]
I tried to compile but when running make in Ubunut 20.04 I get this error:
```
$ make
glib-compile-resources --target=./src/resources.c --sourcedir=./data/ --generate data/resources.xml 
gcc -Wall -g -o `pkg-config --cflags gtk+-3.0 libcrypto`   -c -o src/dmr/BPTC19696.o src/dmr/BPTC19696.c
Package libcrypto was not found in the pkg-config search path.
Perhaps you should add the directory containing `libcrypto.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcrypto' found
In file included from src/dmr/BPTC19696.h:23,
                 from src/dmr/BPTC19696.c:22:
src/dmr/../main.h:6:10: fatal error: gtk/gtk.h: El fitxer o directori no existeix
    6 | #include <gtk/gtk.h>
      |          ^~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: src/dmr/BPTC19696.o] Error 1
```
What can I do? I installed libcrypto++-dev 
```
sudo apt install libcrypto++-dev

```
but did not help.
Thanks!

**Comment by mlforcada** [comment]
Found the way:
```
sudo apt install libssl-dev
```
does the trick!

**Comment by ea3ihi** [comment]
Hello Mikel, your issue arrived just at the right time, nice that you have solved it on your own. It was yesterday that I have been compiling for a Ubuntu 20.04 Linux  desktop and we also found some issues with the ssl library. Soon I will update the makefile and add some instructions regarding ssl.

**Comment by ea3ihi** [comment]
Just a hint, when using DMRStation on a standard desktop set decorated=1 in the UI section of the ini file to allow standard application window behaviour.
