### ISSUE TITLE
The project link in the readme is broken

### ISSUE THREAD

**Issue by fossum** [ea3ihi/DMRStation#12]
The main project link (http://dmrstation.com/) in the readme file redirects a bunch of times before going nowhere helpful.

Is there a project URL anymore?

**Comment by dtemes** [comment]
I left the domain expire due to the little traction of the project, now the website can be found here:

[http://dmrstation.ea3ihi.es](http://dmrstation.ea3ihi.es)

(Looks like the old dmrstation.com domain was interesting enough for someone to register it and try to sell it.)

**Comment by ea3ihi** [comment]
readme.md updated!
