### ISSUE TITLE
Display callsing and name

### ISSUE THREAD

**Issue by sp2ong** [ea3ihi/DMRStation#5]
Hi

It could be displayed on the main window when instead of DMR ID there is a visible callsign to add a name in one row as it is on the radio display . Data is taken from DMRIds.dat

**Comment by ea3ihi** [comment]
Usually if you have a bigger screen and you are in the last heard tab you can see this information, but it is a good suggestion.

**Comment by sp2ong** [comment]
Yes, but in Mini and Micro we do not have the lastheard online view and it will be nice to see the name in these UI :-)

**Comment by ea3ihi** [comment]
Added a second line in the id label with the user name
