### ISSUE TITLE
TX And Audio Bug 

### ISSUE THREAD

**Issue by MM6NRK** [ea3ihi/DMRStation#6]
On  TX i get  about 2 overs then the no audio on TX kicks in again . Mine is doing the same as TA2EI 
.
Some times i get audio and most of the time nothing .
I have used two usb sound cards and two mics and it still the same .Some times when i hit PTT it keys up then cuts out after 1 sec .

----------

From TA2EI 

My experiments focused on RX firstly. Then I've started trying TX. I've preffered Parrot channel for TX experiments. These are my results:

Despite many TX I've heard myself just two times over parrot. Other transmissions are lost. (?)

After parrot channel I've tried a local TG. Some transmissions are heard but some of them are lost. (?)

Anyway, from time to time I've received "user blocked" messages despite no TX made by me.

**Comment by MM6NRK** [comment]
By 
LB9AB » Sat May 30, 2020 6:39 pm

Great work!
I have installed DMRStation on Raspberry Pi 4 and use a USB Jabra conference speaker with microphone. The RX sound is great!

When I select new talk group DMRStation sends and connects normally. When I press PTT on the screen with the mouse, it looks like it's sending, and the command line interface says it's in TX (PTT ON), but it doesn't send anything out. Are there any settings in DMRStation.ini I need to change for this to work on Raspberry Pi 4 ?

Incredibly great software, keep up the great work!

Here is my video: https://www.youtube.com/watch?v=AV8B8SjGtDA&feature=youtu.be

**Comment by ea3ihi** [comment]
There are no special settings that I know to make the app work with pi4, it should work without problem. 

If the voice header frames and voice terminator is send but there is nothing in between then I suspect it is related to the audio. I have read that some audio cards can not work at 8khz, but I don't think this is your case, and also too many casualties that you have problems with all your audio devices.

One of the things I would like to add is a tab with the audio settings, i think it will help.

**Comment by ea3ihi** [comment]
Good news and bad news, testing again with my pi3 and have the same sporadic behaviour and for instance the parrot many times does not send the echo response back. However I can see that there is network traffic.
In order to better test I have connected some devices to my own "master" server (running my own version of hblink, the code is also available in my github). The results is that I can always hear the transmissions from my rpi3 without issues.

So I guess there is something in the information sent that the brandmeister network does not like. It might be a timing issue.

The good news is that now I have the environment to troubleshoot the issue. Sorry for all the inconveniences.

**Comment by MM6NRK** [comment]
Keep up the good work David and no need to say sorry for inconveniences .

I think your right about the information sent that the brandmeister network does not like.

**Comment by ea3ihi** [comment]
Can you please test this version? 

https://github.com/ea3ihi/DMRStation-release/blob/master/DMRstation

I am getting very good results talking with the parrot.

I have changed the way the voice headers are sent. Before the header was sent right after pressing the ptt button, then the audio stream is uncorked and when audio starts to flow the voice frames are sent. It seems that for some reason many times the audio takes a little longer to flow than expected so there might be a delay between the voice header and the voice frames that the DMR master might not like.

Now the voice headers are not sent straight on after pressing the ptt, but right before the first audio frame is sent.

**Comment by MM6NRK** [comment]
Ok it works as it should now but seen this warning on start up .

This has fixed the Audio TX 

-----
(DMRstation:1039): GLib-WARNING **: 12:24:52.847: GError set over the top of a previous GError or uninitialized memory.
This indicates a bug in someone's code. You must ensure an error is NULL before it's set.
The overwriting error message was: Key file does not have group “codec2”
TG is 0!
Sending auth
State 1
Sink 0: alsa_output.usb-C-Media_Electronics_Inc._USB_PnP_Sound_Device-00.analog-stereo
CM108 Audio Controller Analog Stereo
Sink 1: alsa_output.platform-soc_audio.analog-mono
Built-in Audio Analog Mono
Source 0: alsa_output.usb-C-Media_Electronics_Inc._USB_PnP_Sound_Device-00.analog-stereo.monitor
Monitor of CM108 Audio Controller Analog Stereo
Source 1: alsa_input.usb-C-Media_Electronics_Inc._USB_PnP_Sound_Device-00.analog-mono
CM108 Audio Controller Analog Mono
Source 2: alsa_output.platform-soc_audio.analog-mono.monitor
Monitor of Built-in Audio Analog Mono
Record stream ready
State 2
Send config
Connected
TG is 0!

**Comment by MM6NRK** [comment]
Here is a video of my test and everything works fine on TX .

https://www.youtube.com/watch?v=AfmLaTJSjgg

**Comment by ea3ihi** [comment]
Thanks for the report. Ignore the warning, it is due to new settings needed in the ini file in near future changes. Those changes are related to "codec2". I will close this issue.

**Comment by MM6NRK** [comment]
Ok thanks again for your help .

Fixed

**Comment by RecepAGulec** [comment]
Hi,
I've tested the new DMRstation (v0.9) on a RPİ3 and RPi4.
I've received all TX echoes on the Parrot ch.
TX on a local TG is good.

These are RPi3 messages:
-------------------------------------------------------------
DMRstation:1075): GLib-WARNING **: 15:45:12.226: GError set over the top of a previous GError or uninitialized memory.
This indicates a bug in someone's code. You must ensure an error is NULL before it's set.
The overwriting error message was: Key file does not have group ?codec2?
...
Selected tg 91
DMR status 1
DMR status 1
DMR status 1
DMR status 0
State 4
Segmentation fault
pi@raspberrypi:/opt/DMRStation $ 
-------------------------------------------------------

And these are RPi4 messages:
---------------------------------------------------------
(DMRstation:890): GLib-WARNING **: 15:59:48.155: GError set over the top of a previous GError or uninitialized memory.
This indicates a bug in someone's code. You must ensure an error is NULL before it's set.
The overwriting error message was: Key file does not have group ?codec2?

(DMRstation:890): GLib-WARNING **: 15:59:48.155: GError set over the top of a previous GError or uninitialized memory.
This indicates a bug in someone's code. You must ensure an error is NULL before it's set.
The overwriting error message was: Key file does not have key ?decorated? in group ?ui?
...
Connected
DMR status 1
DMR status 1
DMR status 1
DMR status 0
DMR status 1
State 4
Segmentation fault
pi@raspberrypi:/opt/DMRStation $ 
--------------------------------------------------------------
Thanks for your efforts.
Regards.

**Comment by sp2ong** [comment]
David,

Please update sources to latest version I would like compile this version for my Orange Pi Zero

Thank you

**Comment by MM6NRK** [comment]
Hi david i think this should be the 1st thing you install before anything to stop any crashing . Could you add these to install Info ?

sudo apt-get install at-spi2-core

For some reason i had to install pulseaudio again after install 

sudo apt-get install pulseaudio

**Comment by ea3ihi** [comment]
Source updated!

**Comment by Jumbotroll** [comment]
Great work again!
Tested v.09 on Raspberry Pi 4 with Jabra speaker on Norwegian Parrot and TX audio was ok.
https://youtu.be/xxdPDc59JGc

**Comment by ea3ihi** [comment]
Thanks for the report. Those Jabra speakers sound really nice. With such a big screen why are you using the smallui screen option?

**Comment by Jumbotroll** [comment]
> Thanks for the report. Those Jabra speakers sound really nice. With such a big screen why are you using the smallui screen option?

The screen I'm using is on my Mac pro. Running VNC remote to Raspberry Pi 4 :-)
I'm going to get an HDMI screen for my Raspberry later :-)
Thanks for great work!

**Comment by ea3ihi** [comment]
I would suggest to use the bigger UI and also set decorated=1 in the UI options while in your Mac like:

```
[ui]
smallUI=0
decorated=1
```

**Comment by Jumbotroll** [comment]
> I would suggest to use the bigger UI and also set decorated=1 in the UI options while in your Mac like:
> 
> ```
> [ui]
> smallUI=0
> decorated=1
> ```

Thanks! That look much better!

**Comment by sp2ong** [comment]
Hi David

> Source updated! 

Thanks
I have seen you add Codec2 

Can you write more about use Codec2 in DMRStation?

I know one project opensource M17 which use Codec2 as base codec 
it maybe it will be nice in future support M17 in DMRStation :-)

https://m17project.org/
https://m17project.org/forum/
https://github.com/sp5wwp

**Comment by ea3ihi** [comment]
I will take a look at the M17 project, I think we share some ideas. The
AMBE codec is preventing free investigation and experiment ation in the
digital ham radio world. The DMR standards from ETSI do not impose any
codec, so AMBE can be substituted with codec2 or any other codec while
keeping everything else intact.

I have already maintained some conversations with the parrot using codec2
and it just works. The quality has dropped a bit but is usable. My approach
has been to create a codec2 UDP server than works exactly as the md380
emulator, so one can substitute the other. Now I am just preparing some
settings and auxiliary code to use one codec or the other by just changing
a configuration within the DMRStation app.

David

**Comment by sp2ong** [comment]
Hi David,

It looks like M17 project use Codec2 3200 bit/s but the M17 specification is subject to change. A variable bitrate may be supported in the future.
On the page: http://www.rowetel.com/wordpress/?p=5520 
we can listen quality compare Codec2 3200 bit/s versus AMBE+ 2400 (DMR)
