### ISSUE TITLE
Talk Groups 

### ISSUE THREAD

**Issue by MM6NRK** [ea3ihi/DMRStation#8]
Hi is there a limit on how many Talk Groups you can add ? 
I was trying to add then all from the Brandmister network  but only so many show up .
There are 1541 available TalkGroups on the BrandMeister network.

**Comment by ea3ihi** [comment]
I added a limit of 150 groups, more than enough. Having all the groups
makes no sense (for me) as usually you just use a few of them, and at some
point we will have the option to enter the tg manually.

**Comment by MM6NRK** [comment]
Ok thanks .
